; PlatformIO project configuration
; Docs: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    ; e.g. bblanchon/ArduinoJson

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp8266]
platform = espressif8266
board = nodemcuv2
